# food = [
    # "chicken",
    # "rice",
    # "bread"
# ]

# transport = [
    # "taxi",
    # "bus",
    # "airplane"
# ]

# electricity = [
    # "electricity",
    # "electric",
    # "electrici"
# ]
food = [
    "amaranto",
    "arroz",
    "avena ",
    "tortillas de maíz ",
    "pan integral",
    "fideos/pasta",
    "cereales de harina integral",
    "buñuelos",
    "muffins",
    "tortillas de harina",
    "churros",
    "pan blanco",
    "pan dulce",
    "cereales con azúcar",
    "bolillos",
    "maracuyá",
    "arepas",
    "bananos",
    "chirimoya",
    "durazno",
    "fresas",
    "granadilla",
    "guayaba",
    "limón",
    "mango",
    "manzana",
    "melón",
    "naranja/china",
    "nectarina",
    "papaya",
    "pasas",
    "pera",
    "piña",
    "uva",
    "zapote",
    "aguacate",
    "coco",
    "berenjena",
    "brécol/brocoli",
    "camote",
    "cebolla ",
    "chayote ",
    "espárrago",
    "hongos",
    "jícama",
    "lechuga",
    "maíz",
    "malanga",
    "nopales",
    "pana",
    "papas",
    "pepino",
    "pimentón",
    "plátanos",
    "repollo",
    "tomate/tomatillo",
    "yautía ",
    "yuca ",
    "zanahoria",
    "tofu",
    "pavo o guajolote",
    "pollo",
    "pescado",
    "mariscos",
    "huevos",
    "mantequilla de cacahuate",
    "nueces",
    "chorizo",
    "menudo",
    "res",
    "puerco",
    "margarina",
    "aceite",
    "manteca",
    "olivas/aceitunas ",
    "salsa/aderezo de ensalada",
    "aguacate",
    "mantequilla",
    "queso crema",
]

gasoline = [
    "alcampo",
    "ballenoil",
    "eroski",
    "saras",
    "shell",
    "carrefour",
    "avia",
    "galp",
    "bp",
    "cepsa",
    "campsa",
    "repsol",
    "petronor",
]


electricity = [
    "endesa",
    "iberdrol",
    "edp",
    "bassols",
    "electra",
    "electra",
    "electra",
    "285",
    "electra",
    "eléctrica",
    "estabanell",
    "electrica",
    "hidroeléctrica",
    "comercializadora",
    "comercializadora",
    "eosa",
    "iberdrola",
    "arcos",
    "electrica",
    "aduriz",
    "empresa",
    "gaselec",
    "electra",
    "enercoluz",
    "factor",
    "alpapat",
    "engie",
    "alpiq",
    "union",
    "electra",
    "naturgy",
    "navarro",
    "epresa",
    "edp",
    "nexus",
    "hidroelectrica",
    "bp",
    "agr",
    "edp",
    "eléctrica",
    "electrica",
    "electrica",
    "fluid",
    "global3",
    "electradistribución",
    "electracomercial",
    "axpo",
    "cepsa",
    "energya",
    "factor",
    "repsol",
    "wind",
    "energya",
    "enel",
    "endesa",
    "acciona",
    "atel",
    "energya",
    "morgan",
    "gdf",
    "geoatlanter",
    "fortia",
    "constellation",
    "gesternov",
    "viacav",
    "rwe",
    "baser",
    "escandinava",
    "régsiti",
    "cide",
    "energia",
    "alpiq",
    "accord",
    "barclays",
    "bp",
    "compagnie",
    "danske",
    "edp",
    "ed",
    "electrabe",
    "uniper",
    "edf",
    "electricité",
    "elektrizität",
    "enbw",
    "endesa",
    "enel",
    "enel",
    "kalibra",
    "merril",
    "morgan",
    "office",
    "rede",
    "rwe",
    "shell",
    "sonelgaz ",
    "statkraft",
    "total",
    "electrica",
    "hidroelectrica",
    "electrica",
    "sociedad",
    "energias",
    "electra",
    "hidroelectrica",
    "curenergía",
    "distribucion",
    "comercializadora",
    "societat",
    "electra",
    "eléctrica",
    "distribuidora",
    "electrica",
    "energy",
    "distribuidora",
    "orus",
    "elèctrica",
    "cateneribas",
    "estabanell",
    "municipal",
    "energias",
    "comercializadora",
    "societat",
    "electrica",
    "talarn",
    "distribuidora",
    "empresa",
    "electrica",
    "electrica",
    "compañía",
    "empresa",
    "comercializadora",
    "gazprom",
    "servicios",
    "gas",
    "madrileña",
    "db",
    "nexus",
    "naturgy",
    "saltos",
    "hidroelectrica",
    "ab",
    "lonjas",
    "hidroeléctrica",
    "geoatlanter",
    "elecva",
    "ae3000",
    "electrica",
    "electrica",
    "electrica",
    "electrica",
    "cooperativa",
    "distribuidora",
    "electrica",
    "comercial",
    "electrodistribuidora",
    "electrica",
    "evergreen",
    "villar",
    "suministros",
    "electricas",
    "eléctrica",
    "audax",
    "audax",
    "syder",
    "eléctrica",
    "utility",
    "gestiner",
    "electrica",
    "electrica",
    "international",
    "sanjosé",
    "respira",
    "eléctricas",
    "llum",
    "fluido",
    "coop",
    "fenie",
    "enara",
    "alpiq",
    "electro",
    "electro",
    "holalu",
    "eléctricas",
    "iposta",
    "energia",
    "celtica",
    "aracan",
    "grupo",
    "som",
    "aura",
    "galp",
    "aayum",
    "cooperativa",
    "mallorquina",
    "sampol",
    "nordjysk",
    "gem",
    "dreue",
    "forces",
    "zeltria",
    "switch",
    "electrica",
    "knet",
    "energías",
    "eléctrica",
    "canary",
    "edp",
    "gdf",
    "zence",
    "gestionna",
    "electrourbano",
    "cooperativa",
    "ecoeq",
    "holding",
    "sunair",
    "compañia",
    "unielectrica",
    "olte",
    "comercializadora",
    "electrica",
    "vóltico",
    "laboil",
    "watiu",
    "gnera",
    "energias",
    "ampere",
    "carvisa",
    "solvay",
    "alcanzia",
    "xenera",
    "atlas",
    "europa",
    "iner",
    "goiener",
    "electro",
    "vertsel",
    "euroenergia",
    "stagioni",
    "aurora",
    "adelfas",
    "iberoelectra",
    "bkw",
    "integración",
    "indexo",
    "mercuria",
    "concis",
    "the",
    "ninobe",
    "cye",
    "solelec",
    "watio",
    "nueva",
    "energy",
    "corpolu",
    "distribuciones",
    "dxt",
    "foener",
    "eléctrica",
    "eléctricas",
    "comercializadora",
    "comercializadora",
    "electrica",
    "nortedison",
    "centrica",
    "conecta2",
    "tecnos",
    "electrica",
    "energia",
    "insignia",
    "corporación",
    "petronieves",
    "energi",
    "another",
    "siesta",
    "catralense",
    "energia",
    "energest",
    "energía",
    "ads",
    "aldro",
    "empresa",
    "sunair",
    "suministros",
    "comercializadora",
    "avanzalia",
    "energy",
    "im3",
    "iberdrola",
    "iberdrola",
    "comercializadora",
    "aldefe",
    "nemon",
    "eleva",
    "iberelectrica",
    "energia",
    "eneluz",
    "telefónica",
    "daimuz",
    "adixa",
    "elecnova",
    "ledesma",
    "multienergia",
    "energía",
    "comercializacion",
    "teramelcor",
    "luci",
    "puerta",
    "estrategias",
    "adetec",
    "global",
    "iniciativa",
    "the",
    "jorge",
    "comercializador",
    "hefameco",
    "energía",
    "enerxia",
    "trailstone",
    "rofeica",
    "servigas",
    "sunair",
    "horeca",
    "aserval",
    "enerplus",
    "nobe",
    "mi",
    "eleva",
    "energysave",
    "loop",
    "ayluz",
    "alterna",
    "ingeniería",
    "cox",
    "elygas",
    "inserimos",
    "pulsar",
    "energetica",
    "pepeenerg",
    "renewable",
    "gaolania",
    "accion",
    "energía",
    "electrica",
    "alnair",
    "electiaplus",
    "electroroute",
    "apeles",
    "noble",
    "suministradora",
    "aboutwhite",
    "28823",
    "adeinnova",
    "beta",
    "prot",
    "nosa",
    "fox",
    "aqui",
    "solar",
    "luvon",
    "elegrand",
    "energika",
    "premium",
    "export",
    "unic",
    "electrica",
    "trade",
    "ronda",
    "emasp",
    "luzdeaqu",
    "enstrog",
    "cemoi",
    "catgas",
    "gestiona",
    "neoelectra",
    "optimus",
]


transport = [
    "bus",
    "avion",
    "barco",
    "coche",
    "taxi",
    "abarth",
    "acura",
    "csx",
    "integra",
    "legend",
    "mdx",
    "rdx",
    "rl",
    "rsx",
    "alfa romeo",
    "ar6",
    "ar8",
    "brera",
    "giulietta",
    "gt",
    "gtv",
    "milano",
    "mito",
    "spider",
    "alpina",
    "american motors",
    "amx",
    "javelin",
    "pacer",
    "rebel",
    "aston martin",
    "audi",
    "allroad quattro",
    "cabriolet",
    "coupe",
    "coupe quattro",
    "e-tron",
    "tt roadster",
    "bentley",
    "continental",
    "flying spur",
    "bmw",
    "buick",
    "apollo",
    "cascada",
    "centurion",
    "century",
    "electra",
    "enclave",
    "encore",
    "excelle",
    "invicta",
    "lacrosse",
    "lesabre",
    "lucerne",
    "park avenue",
    "rainier",
    "reatta",
    "regal",
    "rendezvous",
    "riviera",
    "roadmaster",
    "skyhawk",
    "skylark",
    "special",
    "super",
    "terraza",
    "verano",
    "wildcat",
    "cadillac",
    "ats",
    "brougham",
    "calais",
    "catera",
    "cimarron",
    "ct6",
    "cts",
    "deville",
    "dts",
    "eldorado",
    "elr",
    "escalade",
    "fleetwood",
    "series 62",
    "seville",
    "srx",
    "sts",
    "xlr",
    "xt4",
    "xt5",
    "xts",
    "chevrolet",
    "astro",
    "avalanche",
    "avalanche black diamond",
    "aveo",
    "bel air",
    "beretta",
    "biscayne",
    "blazer",
    "brookwood",
    "c10 pickup",
    "c10 suburban",
    "c1500",
    "c1500 suburban",
    "c20 pickup",
    "c20 suburban",
    "c2500",
    "c2500 pickup",
    "c2500 suburban",
    "c30 pickup",
    "c3500",
    "c3500 pickup",
    "c4500 kodiak",
    "c5500 kodiak",
    "camaro",
    "caprice",
    "captiva",
    "captiva sport",
    "cavalier",
    "celebrity",
    "chevelle",
    "chevette",
    "chevy",
    "cheyenne",
    "city express",
    "classic",
    "cobalt",
    "colorado",
    "combo",
    "corsa",
    "corsica",
    "corvette",
    "cruze",
    "el camino",
    "epica",
    "equinox",
    "evanda",
    "express 1500",
    "express 2500",
    "express 3500",
    "express 4500",
    "g10",
    "g20",
    "g30",
    "hhr",
    "impala",
    "impala limited",
    "k1500",
    "k2500",
    "k3500",
    "k5 blazer",
    "kalos",
    "kingswood",
    "lacetti",
    "laser",
    "llv",
    "lumina",
    "luv",
    "malibu",
    "matiz",
    "meriva",
    "metro",
    "montana",
    "monte carlo",
    "n300",
    "nova",
    "nubira",
    "optra",
    "orlando",
    "p10",
    "p20",
    "p30",
    "rezzo",
    "s-10",
    "silverad",
    "sonic",
    "spark",
    "sprint",
    "ss",
    "ssr",
    "suburban",
    "tacuma",
    "tahoe",
    "tornado",
    "townsman",
    "tracker",
    "trailblazer",
    "traverse",
    "trax",
    "uplander",
    "vectra",
    "vega",
    "venture",
    "vivant",
    "volt",
    "zafira",
    "chrysler",
    "aspen",
    "cirrus",
    "concorde",
    "conquest",
    "cordoba",
    "crossfire",
    "fifth avenue",
    "grand voyager",
    "intrepid",
    "lebaron",
    "lhs",
    "neon",
    "new yorker",
    "newport",
    "pacifica",
    "pt cruiser",
    "sebring",
    "town & country",
    "voyager",
    "citroen",
    "berlingo",
    "bx",
    "aircross",
    "picasso",
    "aircross",
    "cactus",
    "grand picasso",
    "picasso",
    "c-elysee",
    "evasion",
    "jumper",
    "jumpy",
    "nemo",
    "saxo",
    "spacetourer",
    "visa",
    "xantia break",
    "xm-xm break",
    "xsara",
    "xsara picasso",
    "zx",
    "dacia",
    "duster",
    "lodgy",
    "logan",
    "logan mcv",
    "pick-up",
    "sandero",
    "solenzo",
    "daewoo",
    "cielo",
    "damas",
    "espero",
    "fso",
    "kalos",
    "korando",
    "lacetti",
    "lanos",
    "leganza",
    "lublin",
    "matiz",
    "musso",
    "nexia",
    "nubira",
    "pick-up",
    "polonez",
    "rezzo",
    "tico",
    "daihatsu",
    "charade",
    "extol",
    "hi-jet",
    "materia",
    "sirion",
    "terios",
    "yrv",
    "dodge",
    "aries",
    "aspen",
    "atos",
    "attitude",
    "avenger",
    "b100",
    "b200",
    "b300",
    "caliber",
    "caravan",
    "challenger",
    "charger",
    "coronet",
    "d100",
    "d150",
    "d200",
    "d250",
    "d300",
    "d350",
    "dakota",
    "dart",
    "daytona",
    "dinasty",
    "diplomat",
    "durango",
    "grand caravan",
    "h100",
    "imperial",
    "intrepid",
    "i10",
    "journey",
    "lebaron",
    "magnum",
    "monaco",
    "neon",
    "new yorker",
    "nitro",
    "omni",
    "phantom",
    "polara",
    "ram 1500",
    "ram 2500",
    "ram 3500",
    "ram 4500",
    "ram 50",
    "ram 5500",
    "ramcharger",
    "rampage",
    "shadow",
    "sprinter 2500",
    "sprinter 3500",
    "sprit",
    "stealth",
    "stratus",
    "eagle",
    "summit",
    "talon",
    "vision",
    "vista",
    "edsel",
    "citation",
    "corsair",
    "pacer",
    "ranger",
    "roundup",
    "villager",
    "fiat",
    "panorama",
    "familiare",
    "panorama",
    "mirafiori",
    "panorama",
    "albea",
    "barchetta",
    "bravo",
    "bravo & brava",
    "cinquecento",
    "coupe",
    "croma",
    "doblo",
    "doblo mpv",
    "ducato",
    "duna",
    "egea",
    "fiorino",
    "fiorino nuovo",
    "freemont",
    "fullback",
    "grande punto",
    "idea",
    "linea",
    "marea",
    "multipla",
    "palio",
    "panda",
    "pratico",
    "premio",
    "punto",
    "punto evo",
    "qubo",
    "regata",
    "ritmo",
    "scudo",
    "sedici",
    "seicento",
    "siena",
    "slx",
    "stilo",
    "strada",
    "talento",
    "tempra",
    "tipo",
    "ulysse",
]
